disabled_rules:
 - trailing_whitespace
 - todo
  
excluded:
  - Pods

identifier_name:
  min_length:
    error: 3
  excluded:
    - id

function_body_length:
  warning: 80
  error: 200

reporter: "xcode"
